load_id : 1   # Choose Load 1,2,3

input:
  frequency: 200

  type: 1     # 0: 'step' | 1: 'chirp'
  centre_point: 3.1415926536

  # Params for random step input
  step:
    frequency: 5
    variance: 0.3

  # Params for chirp input
  chirp:
    amplitude: 0.5
    frequency1: 10
    frequency2: 40
    period: 2