load_id : 1   # Choose Load '1','2','3', or '0' for no load

control_frequency: 200 # Frequency of input signal to motor (should be 200 Hz)

input_type: 3     # 0: 'step' | 1: 'chirp' | 2: 'flight_data' | 3: 'mixed input' 

