load_id : 1   # Choose Load '1','2','3', or '0' for no load

input:
  frequency: 200

  type: 0     # 0: 'step' | 1: 'chirp'
  centre_point: 0

  # Params for random step input
  step:
    frequency: 5
    variance: 0.1

  # Params for chirp input
  chirp:
    amplitude: 0.5
    frequency1: 10
    frequency2: 40
    period: 2